{% set name = "amgx_custom" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/NVIDIA/AMGX.git
  git_rev: main

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cuda-nvcc 12.*
    - cmake
    - make
  host:
    - cuda-version 12.*
    - cuda-cudart-dev 12.*
    - cuda-libraries-dev 12.*
    # --- A CORREÇÃO FINAL ---
    - cuda-nvtx-dev 12.* # <--- Adicione isto para corrigir o erro nvtxRangeId_t
    # ------------------------

about:
  home: https://github.com/NVIDIA/AMGX
  summary: "NVIDIA AMGX Library (Custom Build)"
  license: BSD-3-Clause
